/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "976px",
      xl: "1440px",
    },
    colors: {
      body_light_background: "#F8F7FC",
      body_dark_background: "#141625",
      sideBar_light_background: "#363B54",
      sideBar_dark_background: "#1E213B",
      purpleMainColor: "#7A5DF5",
      invoiceItem_light_background: "#FFFFFF",
      invoiceItem_dark_background: "#1E213B",
      invoiceForm_light_background: "",
      invoiceForm_dark_background: "#141625",
      darkishBlue_font: "#2E2F33",
      lightGrey_font: "#C8C7CE",
      darkWhite_font: "#EAEEF3",
      grey_font: "#696B86",
      paidLabel_light_background: "#EBFEF8",
      paidLabel_dark_background: "#17303E",
      paidLabel_light_font: "#63B99C",
      paidLabel_dark_font: "#478F8C",
      pendingLabel_light_background: "#FFFADF",
      pendingLabel_dark_background: "#382B2A",
      pendingLabel_light_font: "#D6A25E",
      pendingLabel_dark_font: "#C4925F",
      draftLabel_light_background: "#F6F5FA",
      draftLabel_dark_background: "#292C43",
      draftLabel_light_font: "#434249",
      draftLabel_dark_font: "#EAEEF3",
      nextArrow_light_font: "#C2BED4",
      nextArrow_dark_font: "#433F73",
      deleteBtn_background: "#EC5A5C",
      editBtn_light_background: "#F9FBFF",
      editBtn_light_font: "#C8C8D5",
      profileImg_separator: "#898CB2",  
    },
    extend: {},
  },
  plugins: [],
}
