/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px"
    },
    colors: {
      body_light_background: "#F8F7FC",
      body_dark_background: "#141625",
      sideBar_light_background: "#363B54",
      sideBar_dark_background: "#1E213B",
      purpleMainColor: "#7C5DFA",
      invoiceItem_light_background: "#FFFFFF",
      invoiceItem_dark_background: "#1F213A",
      invoiceForm_light_background: "",
      invoiceForm_dark_background: "#141625",
      darkishBlue_font: "#2E2F33",
      lightGrey_font: "#C8C7CE",
      white: "#FFFFFF",
      darkWhite_font: "#EAEEF3",
      grey_font: "#696B86",
      paidLabel_light_background: "#F3FCF9",
      paidLabel_dark_background: "#1F2C3F",
      paidLabel_light_font: "#63B99C",
      paidLabel_dark_font: "#23DDA1",
      pendingLabel_light_background: "#FDF7EF",
      pendingLabel_dark_background: "#2D2735",
      pendingLabel_light_font: "#D5A25D",
      pendingLabel_dark_font: "#FF8D01",
      draftLabel_light_background: "#F6F5FA",
      draftLabel_dark_background: "#292C43",
      draftLabel_light_font: "#434249",
      draftLabel_dark_font: "#EAEEF3",
      nextArrow_light_font: "#C2BED4",
      nextArrow_dark_font: "#433F73",
      deleteBtn_background: "#EC5A5C",
      editBtn_light_background: "#F9FBFF",
      editBtn_dark_background: "#252A43",
      editBtn_light_font: "#C8C8D5",
      profileImg_separator: "#898CB2", 
      invoiceAmount_light_background: "#F9FAFE",
      invoiceAmount_dark_background: "#252945",
    },
    extend: {},
  },
  plugins: [],
}
